### ISSUE TITLE
Rename question

### ISSUE THREAD

**Issue by tmitchell1** [GoMexSI/gomexsi-web#103]
We are getting ready to start extraction of references for other taxa. All the references extracted to this point have been for fish. In order to distinguish between the taxa, we have added a 4 characters to the beginning of the REF_ID.
EX: Fish = ACT_ ; Birds = AVE_ ; etc
When I start adding the characters, will that upset the availability of the data through the webpage?

**Comment by jhpoelen** [comment]
Please provide a full example.

**Comment by tmitchell1** [comment]
Current name - 25m
New name - ACT_25M

**Comment by jhpoelen** [comment]
@tmitchell1 please document current approach on this as discussed in previous meeting. If this issue is resolve, suggest to close it.

**Comment by jhpoelen** [comment]
Closing stale issue.
