### ISSUE TITLE
statistics shown on front page do not include all gomexsi datasets

### ISSUE THREAD

**Issue by jhpoelen** [GoMexSI/gomexsi-web#107]
In comparing GoMexSI contributions in https://globalbioticinteractions.org/status with the front page on http://gomexsi.tamucc.edu , it seems that the stats on GoMexSI web page should be higher than 24k interactions. 

![screenshot from 2017-11-10 07-11-20](https://user-images.githubusercontent.com/1084872/32664606-af989ed8-c5e6-11e7-8c5b-280cf1453abe.png)

**Comment by jhpoelen** [comment]
Root of the issue was that statistics where aggregated by source citation. Now, the statistics are aggregated by sourceId which corresponds to the github org that registers the datasets. For GoMexSI this is ```GoMexSI``` .

**Comment by jhpoelen** [comment]
Changes were applied and statistics now provide a better reflection of the datasets that GoMexSI has contributed: 197 reference, about 2.7k taxa across about 104k interactions. See attached screenshot.

![screenshot from 2017-11-10 08-20-18](https://user-images.githubusercontent.com/1084872/32667741-67a4022a-c5f0-11e7-8bbb-799eff0abe35.png)

**Comment by jsimons9** [comment]
Hi Jorrit,

  Thanks for updating and checking on this – I had noticed the zeros last week but had not said anything.  Also, do those numbers include the data that Michelle extracted??

Thanks,

Jim

**Comment by jhpoelen** [comment]
Yes, they include the datasets extracted by Michelle @iabascal .

**Comment by jsimons9** [comment]
Thanks Jorrit.  I guess you know that those data do not have any spatial data coordinates included, but do have location names.

Jim
