### ISSUE TITLE
remove login requirement

### ISSUE THREAD

**Issue by jhpoelen** [GoMexSI/gomexsi-web#108]
Currently, you need to login to gomexsi.tamucc.edu to be able to access the query pages.

Proposed is to remove the login requirement to allow for open linking into GoMexSI.

As discussed with @jsimons9 @Dengaloo @FIN-JBarile in context of #104 and #105 .

**Comment by jsimons9** [comment]
Yes, I agree, let's remove the login requirement.  I will have to figure out another way to capture emails for the updates.

**Comment by jsimons9** [comment]
Oops, I did not mean to close that!!

**Comment by jhpoelen** [comment]
Now, no login is needed to access the query pages.
