### ISSUE TITLE
query page does not show itemized list when searching by FishBase species id

### ISSUE THREAD

**Issue by jhpoelen** [GoMexSI/gomexsi-web#109]
For some reason, when searching by ```FBC:FB:SpecCode:120``` on GoMexSI Taxonomic Query page, the results are not itemized. For more info see http://gomexsi.tamucc.edu/query-database/taxonomic/?subjectName=FBC%3AFB%3ASpecCode%3A120&allInteractions=on&findPrey=on&filterPrey=&findPredators=on&filterPredators=&serviceType=rest&action=rhm_data_query or attached screenshot.

![screenshot from 2017-11-16 12-04-50](https://user-images.githubusercontent.com/1084872/32913174-67d51312-cac6-11e7-8559-2aae59db0a09.png)

**Comment by FIN-JBarile** [comment]
Hi. I tried the link, too, and got the same issue where results are not presented. The Download raw data link though works. However, from here I get 127 instances recorded. The corresponding csv file has 866 rows.

Anyhow, there is no change in the URL that we will use to link from FB/SLB to GoMexSI as given above and in #104.

**Comment by jhpoelen** [comment]
@FIN-JBarile thanks for trying. I am working on the display issue. Also, please note the difference between instances (specimen) and the rows: some specimen have multiple rows, one row for each item found in the stomach of a specimen.

**Comment by jhpoelen** [comment]
Items are now populating.

![screenshot from 2017-11-16 17-46-43](https://user-images.githubusercontent.com/1084872/32925319-2d0bc8ea-caf6-11e7-8635-51c031aa0c8d.png)

**Comment by jhpoelen** [comment]
Please note that now the result includes the scientific name and common name for specified id (if available). See attached screenshot.

![screenshot from 2017-11-16 18-22-09](https://user-images.githubusercontent.com/1084872/32926261-356b4b6e-cafb-11e7-8421-d7da96f08b20.png)

**Comment by FIN-JBarile** [comment]
Thanks Jorrit. All is good now. I just noted the difference in the number of instances earlier because your first screenshot for the same species had 352 instances.
