### ISSUE TITLE
Prey modifiers not showing up in search results

### ISSUE THREAD

**Issue by jsimons9** [GoMexSI/gomexsi-web#65]
The modifiers for the prey, ie life history stage, physiologic stage, etc are not showing up in the prey output.  The groupings are now occurring, but not the modifiers.  I just did a search on Scomberomorus cavalla, and their are repetitive Actinopterygii but no modifers.  Probably one of them should be "Actinopterygii digestate".

**Comment by jhpoelen** [comment]
Issue was fixed.
