### ISSUE TITLE
Links to SeaLifeBase

### ISSUE THREAD

**Issue by jsimons9** [GoMexSI/gomexsi-web#73]
This is a database similar to Fishbase also operated out of UBC that covers many marine invertebrates and much data also.  I think this, EOL and Fishbase may cover most all taxa we want to include links to.  I don't want to link to strictly taxonomic databases, as that does not really get us much value for the connection.

**Comment by jhpoelen** [comment]
@jsimons9 creating links to SeaLifeBase and fishbase #72 would be easy to establish if the fishbase team decides to let GloBI. This is a decision that is pending. Please contact Deng/Skit about this.

**Comment by jsimons9** [comment]
Hi Jorrit,

  You are busy this morning.  Theresa and I just sat through the first metadata webinar hosted by NOAA.

  I will contact Skit and Deng concerning this issue.

Jim

**Comment by jhpoelen** [comment]
@jsimons9 Taxonomic links to FishBase and SeaLifeBase are now enabled in GloBI (see attached screenshot with links to [great white shark (_Carcharodon carcharias_)](http://fishbase.org/summary/751) and [California sea lion (_Zalophus californianus_)](http://sealifebase.org/summary/69419). The next step is to have your WordPress developer add the functionality to the GoMexSI website. Please let me know who you'd like me to contact to make this happen.

From http://www.globalbioticinteractions.org/?sourceTaxon=Carcharodon%20carcharias&interactionType=eats - 

![screen shot 2016-07-28 at 10 01 42 am](https://cloud.githubusercontent.com/assets/1084872/17221844/68942a74-54aa-11e6-9fc0-3c73ca1cb4c9.png)

**Comment by jsimons9** [comment]
Hi Jorrit,

  This is great news, but we do not have a Wordpress developer yet to replace Reed.

Jim

**Comment by jhpoelen** [comment]
@jsimons9 this would be a great first feature for the TDB developer to be working on. Perhaps @reedhewitt has some suggestions.

**Comment by jsimons9** [comment]
I asked Reed and he did not.  I have not spent any time searching or putting out an ad yet.

BTW, is the call tonight on Skype??  To whom are we calling??

Jim

**Comment by jhpoelen** [comment]
Links to SeaLifeBase are now available when available. See attached screenshot.

![screenshot from 2017-11-15 11-41-57](https://user-images.githubusercontent.com/1084872/32856608-1f5ddf82-c9fa-11e7-8dfa-e504751ea219.png)
