### ISSUE TITLE
"no match" showing up in output

### ISSUE THREAD

**Issue by jsimons9** [GoMexSI/gomexsi-web#82]
In the same query for S. cavalla I am now seeing a large number of "no match" showing up in the prey  listings - had not seen that before.

**Comment by jhpoelen** [comment]
@jsimons9 please confirm that this is still an issue. Otherwise, I suggest to close the issue.

**Comment by jhpoelen** [comment]
@jsimons9 jim shared that no "no match" items have been observed.
