### ISSUE TITLE
Open sub-webs in a different window in Explorer mode

### ISSUE THREAD

**Issue by jsimons9** [GoMexSI/gomexsi-web#84]
A user asked me if we could have the sub-webs in the Explorer mode open up in a different window - or maybe that could be an option.  I think it is a good idea and several others I have mentioned it to agree.  Not sure how difficult that is.

**Comment by reedhewitt** [comment]
In my development copy of the website, I've updated the Explorer mode in two ways:

1. The way to re-center on a new species is now through the "Explore This" link right under the species name. The link can be opened in a new browser tab by right-clicking or control-clicking the link, just like any normal web link. (Before you could not do this.)  I've updated the instructions on the page to reflect this.
<img width="881" alt="explorer mode updated instructions" src="https://cloud.githubusercontent.com/assets/957141/12691005/ae880a54-c6ad-11e5-8d0c-a16fa6449ed6.png">

2. The pop-up "tooltip" appears when you click directly on a species name in Explorer mode, just like in the Taxonomic Query mode.  The tooltip will contain a link to EOL, Fishbase, and SeaLifeBase, if available.
<img width="891" alt="explorer mode tooltip link" src="https://cloud.githubusercontent.com/assets/957141/12691006/ae9efaac-c6ad-11e5-82ad-b96ff24c84e0.png">

**Comment by jsimons9** [comment]
This is looking great Reed.  Thanks.

Jim

**Comment by jhpoelen** [comment]
Closing issue that has been addressed.
