### ISSUE TITLE
Add %N, %Vol and %FO to the csv output

### ISSUE THREAD

**Issue by jsimons9** [GoMexSI/gomexsi-web#89]
It is great that the N, Vol and FO are now in the csv output.  These can be used to calculate the % values listed in the header, but sometimes the % values are the only thing reported, and it is the % values that are used to calculate the IRI.  So, really it is best if both the raw values and the %s are reported.  The % values are next to the raw numbers in the prey spreadsheet.

**Comment by jhpoelen** [comment]
I've added the % values to the csv output. Please note that it'll take GloBI about a day to populate the appropriate values in the fields. Will notify you when population of the values is complete. Thanks for your patience.

I've included a recent download of prey items of Ariopsis felis. Notice that the columns have been added (ending on _percent), but not values are present yet as described earlier.

[Ariopsis_felis_2016_02_10_11-26-52.csv.txt](https://github.com/GoMexSI/gomexsi-web/files/125218/Ariopsis_felis_2016_02_10_11-26-52.csv.txt)

**Comment by jhpoelen** [comment]
Percent values are now available in downloads. Please re-open / comment when the new functionality is not working as expected.
