### ISSUE TITLE
Filter query results by centroid, polygon, or sampling station

### ISSUE THREAD

**Issue by reedhewitt** [GoMexSI/gomexsi-web#93]
Here's an enhancement that has been discussed:

> For the map option on the Taxonomic Query and Spatial Query pages give the user the choice of selecting: study area centroid, study area polygon, and sampling stations (if applicable). This may have to wait until we have the shapefiles in the database. (display only, uses newly exposed polygons associated with centroid as available through GloBI location API)

To clarify, it sounds like the user should be shown a map with all the studies that appear in the map (optionally represented by centroid, polygon, or sampling staitons).  Then the user could select one or more of these items on the map to filter their results.

If this is the case, then I think we may effectively be looking at merging the taxonomic and spatial query pages.  A universal query page could have a map showing all possible data points before the search.  The user could then pre-select the area they want to search in, or just search all available data.  After a search, the map could indicate which areas contain results and which do not.  The user could then select or deselect areas to refine the results.

**Comment by jsimons9** [comment]
Hi Reed, not exactly. What I am referring to is the option for the map that appears for each of the instances recorded in the on screen output.  At present, when one clicks on "Map" one gets the centroid only.  What I am suggesting is to give three options:  The study area centroid, study area polygon, or sampling stations (if any exist - not all studies have stations).  All of these data are recorded in our spreadsheets, and are ingested into GloBI, just a matter of how easy is it to post them to the screen output from the query results.

**Comment by jsimons9** [comment]
Hi Reed,

  I am planning to stop by your place on Friday morning to go over the items I have requested, and perhaps clarify some questions.

Thanks,

Jim

**Comment by reedhewitt** [comment]
Ok, that makes sense.  I'll open a new issue to clarify with Jorrit about how we can get that data out of Globi.
