### ISSUE TITLE
gomexsi.tamucc.edu unresponsive

### ISSUE THREAD

**Issue by jhpoelen** [GoMexSI/gomexsi-web#96]
On 2016-03-28 around 08:17 pacific time, I tried to load http://gomexsi.tamucc.edu and for some reason, the page take at least a minute or two to load. This is a big different from before, where the page was available in a fraction of a second.

Running a ```curl http://gomexsi.tamucc.edu``` did return some html, but only after a long delay.

**Comment by reedhewitt** [comment]
There seems to be a problem with the University's server.  I'm seeing the same delay when I try to access falcon.tamucc.edu or cte.tamucc.edu (another website that I know is on Falcon).  There must be dozens of websites experiencing this problem right now, so odds are that the IT department is working on it.

**Comment by jhpoelen** [comment]
@jsimons9 is there a contact at tamucc IT department we can contact about this? I'd like to make sure that they know about the issue. We might be the first ones noticing it.

**Comment by jsimons9** [comment]
I just spoke with our IT folks and they are having campus wide issues with websites etc at this moment.

For future reference, their email is:  ithelp@tamucc.edu<mailto:ithelp@tamucc.edu>

Thanks,

Jim

**Comment by jhpoelen** [comment]
looks like http://gomexsi.tamucc.edu is back up. Closing issue.
